# See https://sw.kovidgoyal.net/kitty/conf.html
font_family Maple Mono
font_size 12

# Shell integration is sourced and configured manually
shell_integration no-rc

background_opacity 0.9

window_margin_width 10

scrollback_lines 2000

shell_integration enabled

